export function ShareMeta({
  template,
  createdAt,
}: {
  template: string;
  createdAt?: string;
}) {
  return (
    <div
      style={{
        marginBottom: 20,
        color: "#666",
        fontSize: 14,
        display: "flex",
        gap: 12,
        flexWrap: "wrap",
      }}
    >
      <span>Template: {template.toUpperCase()}</span>

      {createdAt && (
        <span>
          Generated: {new Date(createdAt).toLocaleString()}
        </span>
      )}

      <span>Generated by AI</span>
    </div>
  );
}