"""initial tables

Revision ID: 3d72b9115438
Revises: 
Create Date: 2026-03-22 15:53:30.713087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d72b9115438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_chunks', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file_chunks', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_file_chunks_file_id'), table_name='file_chunks')
    op.drop_index(op.f('idx_file_chunks_user_id'), table_name='file_chunks')
    op.drop_constraint(op.f('file_chunks_file_id_fkey'), 'file_chunks', type_='foreignkey')
    op.drop_constraint(op.f('file_chunks_user_id_fkey'), 'file_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'file_chunks', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'file_chunks', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('file_qa_messages', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('file_qa_messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_file_qa_messages_file_id'), table_name='file_qa_messages')
    op.drop_index(op.f('idx_file_qa_messages_user_id'), table_name='file_qa_messages')
    op.drop_constraint(op.f('file_qa_messages_file_id_fkey'), 'file_qa_messages', type_='foreignkey')
    op.drop_constraint(op.f('file_qa_messages_user_id_fkey'), 'file_qa_messages', type_='foreignkey')
    op.create_foreign_key(None, 'file_qa_messages', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'file_qa_messages', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('files', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('files', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('files', 'storage_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('files', 'mime',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('files', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::text"))
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('runs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('runs', 'template',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('runs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.alter_column('runs', 'share_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_runs_share_id'), table_name='runs')
    op.drop_constraint(op.f('runs_share_id_key'), 'runs', type_='unique')
    op.drop_constraint(op.f('runs_user_id_fkey'), 'runs', type_='foreignkey')
    op.drop_constraint(op.f('runs_file_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'runs', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'runs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'runs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('runs_file_id_fkey'), 'runs', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('runs_user_id_fkey'), 'runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('runs_share_id_key'), 'runs', ['share_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_runs_share_id'), 'runs', ['share_id'], unique=False)
    op.alter_column('runs', 'share_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('runs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.alter_column('runs', 'template',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('runs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('files', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'uploaded'::text"))
    op.alter_column('files', 'mime',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('files', 'storage_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('files', 'filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'file_qa_messages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'file_qa_messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('file_qa_messages_user_id_fkey'), 'file_qa_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('file_qa_messages_file_id_fkey'), 'file_qa_messages', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_file_qa_messages_user_id'), 'file_qa_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_file_qa_messages_file_id'), 'file_qa_messages', ['file_id'], unique=False)
    op.alter_column('file_qa_messages', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('file_qa_messages', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'file_chunks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'file_chunks', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('file_chunks_user_id_fkey'), 'file_chunks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('file_chunks_file_id_fkey'), 'file_chunks', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_file_chunks_user_id'), 'file_chunks', ['user_id'], unique=False)
    op.create_index(op.f('idx_file_chunks_file_id'), 'file_chunks', ['file_id'], unique=False)
    op.alter_column('file_chunks', 'embedding',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('file_chunks', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
